server:
  port: 8088

datasource:
  url: localhost:3306/simple_chat

spring:
  datasource:
    username: root
    password: Gepoint
#    Gepoint
    url: jdbc:mysql://${datasource.url}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      max-lifetime: 1770000
      maximumPoolSize: 10
netty:
  port: 8081

logging:
  level:
    com.simple.dao: info
  config: logback.xml

mybatis:
  type-aliases-package: com.simple.model.entity
  mapper-locations:
    - classpath:mapper/*.xml
  type-handlers-package: com.simple.model.enums.converter


mapper:
  mappers:
    - com.simple.core.MyMapper
  not-empty: false
  identity: MYSQL


#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#拦截器的配置
interceptor:
  path : /**
  excludePath : /login,/,/dist/**,/vendor/**,/api/**
