server:
  port: 8099

datasource:
  url: localhost:3306/simple_chat

spring:
  datasource:
    username: root
    password: Gepoint
#    Gepoint
    url: jdbc:mysql://${datasource.url}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      max-lifetime: 1770000
      maximumPoolSize: 10

logging:
  level:
    com.epoint.dao: trace
  config: logback.xml

mybatis:
  type-aliases-package: com.simple.model.entity
  mapper-locations:
    - classpath:mapper/*.xml
#  type-handlers-package: com.epoint.model.enums.converter


mapper:
  mappers:
    - com.simple.core.MyMapper
  not-empty: false
  identity: MYSQL


#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
